import { elementTransitions } from "../animations/elementTransitions.js";
import { gameUI } from "./gameUI.js";

export const startGameUI = () => {
  let container = document.querySelector(".container");
  container.innerHTML = "";

  let title = document.createElement("h1");
  title.textContent = "THE HORROR COUNTER";

  let instructions = document.createElement("p");
  instructions.textContent = `Free your self from the curse!
    Use "+" and "-" buttons or keyboard arrows to choose a number from 1 to 17. 
    If the random value generated by the computer is within that range, 
    you'll win the game.
    
    `;

  let button = document.createElement("button");
  button.textContent = "Start game";
  container.append(title, instructions, button);

  elementTransitions(container);

  button.addEventListener("click", (e) => {
    gameUI(container);
  });
};
